
default:
	@echo -n '$$ '
	cogs factorial 10
	@echo -n '$$ '
	cogs fibonacci 10
	@echo -n '$$ '
	cogs help
	@echo -n '$$ '
	cogs help factorial
	@echo -n '$$ '
	cogs help fibonacci
	@echo -n '$$ '
	-cogs factorial ten
	@echo -n '$$ '
	-cogs factorial -- -10
	@echo -n '$$ '
	-cogs fibonacci ten
	@echo -n '$$ '
	-cogs fibonacci -- -10

